apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
spec:
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: inbfor/ml_model
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
status:
  loadBalancer:
    ingress:
      - ip: 172.21.154.186
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30317
  selector:
    app: ml-model
  type: LoadBalancer

